spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: 123456
    username: root
    url: jdbc:mysql://192.168.43.180/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
#    不返回为空的对象
  jackson:
    default-property-inclusion: non_null
  redis:
      host: 192.168.43.180
      port: 6379


server:
  context-path: /sell

wechat:
  mpAppId: wx4491e2753b46394a
  mpAppSecret: af3ae7184d59433f564ee405bc2f79a3
  mchId: 1409146202
  mchKey: c976503d34ca432c601361f969fd8d85
  keyPath: /var/weixin_cert/h5.p12
  notifyUrl: http://fixed.natapp1.cc/sell/pay/notify
  templateId:
    orderStatus: e-Cqq67QxD6YNI41iRiqawEYdFavW_7pc7LyEMb-yeQ

projectUrl:
    wechatMpAuthorize: http://fixed.natapp1.cc
    wechatOpenAuthorize: http://fixed.natapp1.cc
    sell: http://fixed.natapp1.cc


